extends SceneTree

const WheelConfig = preload("res://scripts/wheel_config.gd")

var failures: Array[String] = []

func _init() -> void:
	_check_contains("scripts/main.gd", "_play_w10_loss_focus", "Wheel 10 focus function exists")
	_check_contains("scripts/main.gd", "and near_jackpot", "Wheel 10 focus only triggers in the near-jackpot zone")
	_check_contains("scripts/main.gd", "var pointer_global := _get_wheel_effect_position()", "Wheel 10 focus targets pointer area")
	_check_contains("scripts/main.gd", "canvas_transform", "Wheel 10 focus uses viewport/camera transform")
	_check_contains("scripts/main.gd", "tween.tween_property(wheel_node, \"position\"", "Wheel 10 focus shakes wheel position")
	_check_contains("scripts/main.gd", "tween.parallel().tween_property(wheel_node, \"scale\"", "Wheel 10 focus scales wheel during tension")
	_check_contains("scripts/main.gd", "get_viewport().canvas_transform = original_canvas_transform", "Wheel 10 focus restores viewport transform")
	_check_contains("scripts/main.gd", "_spawn_particle_burst", "Particle burst helper exists")
	_check_contains("scripts/main.gd", "outcome_label == \"JACKPOT\"", "Jackpot burst trigger exists")
	_check_contains("scripts/main.gd", "_spawn_jackpot_celebration", "Jackpot uses upgraded celebration helper")
	_check_contains("scripts/main.gd", "outcome_label.begins_with(\"x\")", "Multiply burst trigger exists")
	_check_contains("scripts/main.gd", "_spawn_multiplier_celebration", "Multiply uses upgraded burst helper")
	_check_contains("scripts/main.gd", "if reduced_motion_enabled:\n\t\treturn", "Motion polish respects reduced motion")
	_check_contains("scripts/main.gd", "var alpha := 0.42 if muted_flashes_enabled else 0.95", "Particle bursts respect muted flashes")
	_check_contains("scripts/game.gd", "_build_post_outcome_coin_events", "Post-outcome skill coin event helper exists")
	_check_contains("scripts/game.gd", "_add_skill_coin_event(events, \"coin_magnet\", amount)", "Coin Magnet creates a visible coin event")
	_check_contains("scripts/game.gd", "SkillEffects.COIN_MAGNET_ADD_VALUE_PER_LEVEL", "Coin Magnet uses percent of Plus value")
	_check_contains("scripts/game.gd", "_add_skill_coin_event(events, \"sharp_mind\", amount)", "Sharp Mind creates a visible coin event")
	_check_contains("scripts/game.gd", "_make_skill_coin_event(\"free_gift\", free_gift_refund)", "Free Gift creates a visible coin event")
	_check_contains("scripts/game.gd", "_make_skill_coin_event(\"banker\", interest)", "Banker creates a visible coin event")
	_check_contains("scripts/game.gd", "_make_skill_coin_event(\"second_wind\", last_spin_cost)", "Second Wind creates a visible coin event")
	_check_contains("scripts/game.gd", "_apply_coin_events_to_state", "Skill coin events are applied to coins in a final ordered pass")
	_check_contains("scripts/main.gd", "await _play_resolution_events(result.get(\"resolution_events\", []))", "Resolution events play after result polish")
	_check_contains("scripts/main.gd", "resolution_events_in_progress = true", "Main tracks coin resolution animation lock state")
	_check_contains("scripts/main.gd", "wheel_node.call(\"set_spin_locked\", true)", "Main locks wheel interactions while coin resolution animations run")
	_check_contains("scripts/main.gd", "wheel_node.call(\"set_spin_locked\", false)", "Main unlocks wheel interactions after coin resolution animations finish")
	_check_contains("scripts/main.gd", "await _show_skill_coin_delta", "Skill coin events are sequential")
	_check_contains("scripts/main.gd", "skill_icon_frames.get(skill_id)", "Skill coin events target owned skill icons")
	_check_contains("scripts/main.gd", "glow.color", "Skill coin event creates icon glow")
	_check_contains("scripts/main.gd", "tween.tween_property(frame, \"scale\"", "Skill coin event pings icon scale")
	_check_contains("scripts/main.gd", "_setup_background_music", "Background music setup exists")
	_check_contains("scripts/main.gd", "music_player.play()", "Background music starts playback")
	_check_contains("scripts/main.gd", "music_player.stream_paused = music_muted", "Music slider can pause/resume BGM")
	_check_contains("scripts/main.gd", "if not music_muted and was_playing and not music_player.playing", "BGM resumes after unmuting")
	_check_contains("assets/sounds/SOURCES.md", "`background-music.wav`", "BGM source is documented")
	_check_contains("assets/sounds/SOURCES.md", "gain-adjusted", "BGM audibility adjustment is documented")
	_check_contains("assets/sounds/SOURCES.md", "`button-hover.wav`", "Button hover source is documented")
	_check_contains("assets/sounds/SOURCES.md", "`button-press.wav`", "Button press source is documented")
	_check_contains("assets/sounds/SOURCES.md", "CC0", "Sound source ledger includes CC0 licensing")
	_check_file_exists("assets/sounds/background-music.wav", "BGM WAV exists")
	_check_file_exists("assets/sounds/background-music.wav.import", "BGM import sidecar exists")
	_check_file_exists("assets/sounds/button-hover.wav", "Button hover WAV exists")
	_check_file_exists("assets/sounds/button-hover.wav.import", "Button hover import sidecar exists")
	_check_file_exists("assets/sounds/button-press.wav", "Button press WAV exists")
	_check_file_exists("assets/sounds/button-press.wav.import", "Button press import sidecar exists")
	_check_file_exists("scripts/verify_polish_runtime.gd", "Runtime polish verifier exists")
	_check_contains("scripts/verify_polish_runtime.gd", "Polish runtime verification passed.", "Runtime polish verifier has pass output")
	_check_contains("scripts/verify_polish_runtime.gd", "MusicMutedLabel", "Runtime verifier checks muted music warning")
	_check_contains("scripts/verify_polish_runtime.gd", "ResolutionWarningLabel", "Runtime verifier checks resolution warning")
	_check_contains("scripts/verify_polish_runtime.gd", "setting_changed", "Runtime verifier checks live options signals")
	_check_contains("scripts/verify_polish_runtime.gd", "ReducedMotionCheck", "Runtime verifier checks reduced motion checkbox")
	_check_contains("scripts/verify_polish_runtime.gd", "MutedFlashesCheck", "Runtime verifier checks muted flashes checkbox")
	_check_contains("scripts/verify_polish_runtime.gd", "LargeUiTextCheck", "Runtime verifier checks large UI text checkbox")
	_check_contains("scripts/verify_polish_runtime.gd", "Reduced motion checkbox did not emit a reduced_motion setting change", "Runtime verifier checks reduced motion signal")
	_check_contains("scripts/verify_polish_runtime.gd", "Muted flashes checkbox did not emit a muted_flashes setting change", "Runtime verifier checks muted flashes signal")
	_check_contains("scripts/verify_polish_runtime.gd", "Large UI text checkbox did not emit a large_ui_text setting change", "Runtime verifier checks large UI text signal")
	_check_contains("scripts/verify_polish_runtime.gd", "_prepare_isolated_save_settings", "Runtime verifier isolates SaveManager settings")
	_check_contains("scripts/verify_polish_runtime.gd", "TutorialSign", "Runtime verifier checks tutorial sign")
	_check_contains("scripts/verify_polish_runtime.gd", "tutorial_sign_tween", "Runtime verifier checks tutorial sign bobbing")
	_check_contains("scripts/verify_polish_runtime.gd", "history_requested", "Runtime verifier checks run history signal")
	_check_contains("scripts/verify_polish_runtime.gd", "credits_requested", "Runtime verifier checks credits signal")
	_check_contains("scripts/verify_polish_runtime.gd", "tutorial_sign_seen", "Runtime verifier checks tutorial sign dismissal setting")
	_check_contains("scripts/verify_polish_runtime.gd", "Tutorial sign should stay hidden after tutorial_sign_seen is saved", "Runtime verifier checks tutorial sign remains dismissed")
	_check_contains("scripts/verify_polish_runtime.gd", "should not show focus borders before keyboard/controller navigation starts", "Runtime verifier checks mouse-first focus suppression")
	_check_contains("scripts/verify_polish_runtime.gd", "Main scene should focus New Game once keyboard/controller navigation starts", "Runtime verifier checks main-menu focus activates on navigation input")
	_check_contains("scripts/verify_polish_runtime.gd", "Wheel should not allow another spin while coin resolution animations are still counting", "Runtime verifier checks spin lock during coin resolution")
	_check_contains("scripts/verify_polish_runtime.gd", "_expect_focus_neighbor", "Runtime verifier checks explicit focus-neighbor wiring")
	_check_contains("scripts/verify_polish_runtime.gd", "_verify_run_history_runtime", "Runtime verifier checks saved run history behavior")
	_check_contains("scripts/verify_polish_runtime.gd", "Run history should keep exactly 12 newest entries", "Runtime verifier checks history cap")
	_check_contains("scripts/verify_polish_runtime.gd", "\"base_payout\", \"skill_payout\", \"spin_costs\", \"shop_spent\"", "Runtime verifier checks history breakdown fields")
	_check_contains("scripts/verify_polish_runtime.gd", "_verify_end_screen_breakdown_runtime", "Runtime verifier checks end screen breakdown behavior")
	_check_contains("scripts/verify_polish_runtime.gd", "CoinBreakdownTitle", "Runtime verifier checks end screen coin breakdown title")
	_check_contains("scripts/verify_polish_runtime.gd", "End screen should not duplicate Coin Breakdown when populated twice", "Runtime verifier checks end screen breakdown duplicate guard")
	_check_contains("scripts/verify_polish_runtime.gd", "_verify_visual_effect_runtime", "Runtime verifier checks visual effect behavior")
	_check_contains("scripts/verify_polish_runtime.gd", "Music volume zero should stop background music playback", "Runtime verifier checks BGM mute application")
	_check_contains("scripts/verify_polish_runtime.gd", "Music volume above zero should unpause background music", "Runtime verifier checks BGM unpause application")
	_check_contains("scripts/verify_polish_runtime.gd", "SFX volume should apply to result sound players", "Runtime verifier checks SFX volume application")
	_check_contains("scripts/verify_polish_runtime.gd", "Main accessibility settings should enable reduced motion", "Runtime verifier checks main reduced-motion state")
	_check_contains("scripts/verify_polish_runtime.gd", "Main accessibility settings should enable muted flashes", "Runtime verifier checks main muted-flashes state")
	_check_contains("scripts/verify_polish_runtime.gd", "Main accessibility settings should enable large UI text", "Runtime verifier checks main large-text state")
	_check_contains("scripts/verify_polish_runtime.gd", "Large UI text should increase existing main-scene label font size", "Runtime verifier checks main label large-text scaling")
	_check_contains("scripts/verify_polish_runtime.gd", "Main-menu Run History button should open the Run History modal", "Runtime verifier checks real main-menu history button opens modal")
	_check_contains("scripts/verify_polish_runtime.gd", "Main-menu opened Run History modal should show empty state", "Runtime verifier checks real main-menu history empty state")
	_check_contains("scripts/verify_polish_runtime.gd", "Run History modal should open from main scene", "Runtime verifier checks run history modal opens")
	_check_contains("scripts/verify_polish_runtime.gd", "Empty Run History modal should show empty state", "Runtime verifier checks run history empty state")
	_check_contains("scripts/verify_polish_runtime.gd", "Run History modal should show payout breakdown", "Runtime verifier checks run history payout rendering")
	_check_contains("scripts/verify_polish_runtime.gd", "Run History modal should show spend breakdown", "Runtime verifier checks run history spend rendering")
	_check_contains("scripts/verify_polish_runtime.gd", "Run History modal should show saved skill summary", "Runtime verifier checks run history skill rendering")
	_check_contains("scripts/verify_polish_runtime.gd", "Credits modal should show title", "Runtime verifier checks credits modal rendering")
	_check_contains("scripts/verify_polish_runtime.gd", "Save button did not emit save_requested", "Runtime verifier checks explicit save button signal")
	_check_contains("scripts/verify_polish_runtime.gd", "Saved run should restore pending shop availability", "Runtime verifier checks pending shop save restore")
	_check_contains("scripts/verify_polish_runtime.gd", "Main scene should not show coin breakdown outside end/history surfaces", "Runtime verifier checks main has no coin breakdown")
	_check_contains("scripts/verify_polish_runtime.gd", "Main menu should not show coin breakdown", "Runtime verifier checks main menu has no coin breakdown")
	_check_contains("scripts/verify_polish_runtime.gd", "Options modal should not show coin breakdown", "Runtime verifier checks options has no coin breakdown")
	_check_contains("scripts/verify_polish_runtime.gd", "Tutorial modal should not show coin breakdown", "Runtime verifier checks tutorial has no coin breakdown")
	_check_contains("scripts/verify_polish_runtime.gd", "Shop scene should not show coin breakdown", "Runtime verifier checks shop has no coin breakdown")
	_check_contains("scripts/verify_polish_runtime.gd", "_assert_no_runtime_tooltips", "Runtime verifier checks no runtime tooltips")
	_check_contains("scripts/verify_polish_runtime.gd", "Runtime tooltip should be empty", "Runtime verifier reports tooltip regressions")
	_check_contains("scripts/verify_polish_runtime.gd", "_verify_menu_layout", "Runtime verifier checks menu responsive layout")
	_check_contains("scripts/verify_polish_runtime.gd", "_verify_main_layout", "Runtime verifier checks main responsive layout")
	_check_contains("scripts/verify_polish_runtime.gd", "Vector2i(1024, 768)", "Runtime verifier checks narrow resolution layout")
	_check_contains("scripts/verify_polish_runtime.gd", "Vector2i(3440, 1440)", "Runtime verifier checks ultrawide resolution layout")
	_check_contains("scripts/verify_polish_runtime.gd", "should hide the stats panel in compact layout", "Runtime verifier checks compact side-panel behavior")
	_check_contains("scripts/verify_polish_runtime.gd", "should show the stats panel in wide layout", "Runtime verifier checks wide side-panel behavior")
	_check_contains("scripts/verify_polish_runtime.gd", "Jackpot result polish should dispatch the upgraded celebration burst", "Runtime verifier checks jackpot result dispatch")
	_check_contains("scripts/verify_polish_runtime.gd", "Multiplier result polish should dispatch the upgraded burst", "Runtime verifier checks multiplier result dispatch")
	_check_contains("scripts/verify_polish_runtime.gd", "Non-Wheel-10 multiplier result polish should not dispatch Wheel 10 focus movement", "Runtime verifier checks non-W10 multiplier avoids Wheel 10 focus")
	_check_contains("scripts/verify_polish_runtime.gd", "Particle burst should add the requested number of particles", "Runtime verifier checks particle burst count")
	_check_contains("scripts/verify_polish_runtime.gd", "Muted flashes should lower particle alpha to 0.42", "Runtime verifier checks muted flash alpha")
	_check_contains("scripts/verify_polish_runtime.gd", "Reduced motion should suppress particle bursts", "Runtime verifier checks reduced-motion burst suppression")
	_check_contains("scripts/verify_polish_runtime.gd", "Wheel 10 focus should move the wheel or zoom the viewport during the tween", "Runtime verifier checks Wheel 10 focus movement")
	_check_contains("scripts/verify_polish_runtime.gd", "Wheel 10 focus should restore viewport transform", "Runtime verifier checks Wheel 10 focus restoration")
	_check_contains("scripts/verify_polish_runtime.gd", "Reduced motion should suppress Wheel 10 focus movement", "Runtime verifier checks reduced-motion Wheel 10 focus suppression")
	_check_contains("scripts/verify_polish_runtime.gd", "Indicator pulse should create exactly 16 sparkle particles", "Runtime verifier checks indicator sparkle count")
	_check_contains("scripts/verify_polish_runtime.gd", "Indicator pulse should not scale the previous wheel selector", "Runtime verifier checks previous selector untouched")
	_check_contains("scripts/verify_polish_runtime.gd", "Indicator pulse should not scale the next wheel selector", "Runtime verifier checks next selector untouched")
	_check_contains("scripts/verify_polish_runtime.gd", "Successful spin should sparkle the next-wheel arc when a higher wheel becomes affordable", "Runtime verifier checks indicator sparkle trigger")
	_check_contains("scripts/verify_polish_runtime.gd", "Spin should not sparkle the next-wheel arc when highest affordable wheel does not increase", "Runtime verifier checks indicator sparkle non-trigger")
	_check_file_exists("export_presets.cfg", "Export presets file exists")
	_check_contains("export_presets.cfg", "name=\"Windows Desktop\"", "Export presets include Windows desktop target")
	_check_contains("export_presets.cfg", "platform=\"Windows Desktop\"", "Windows export preset platform is declared")
	_check_contains("export_presets.cfg", "name=\"Linux/X11\"", "Export presets include Linux desktop target")
	_check_contains("export_presets.cfg", "platform=\"Linux/X11\"", "Linux export preset platform is declared")
	_check_contains("export_presets.cfg", "application/icon=\"res://assets/ui/game-logo.png\"", "Windows export preset uses shipped logo asset as icon")
	_check_contains("scenes/main.tscn", "res://assets/sounds/background-music.wav", "Main scene references BGM asset")
	_check_contains("scenes/main.tscn", "res://assets/sounds/button-hover.wav", "Main scene references hover SFX asset")
	_check_contains("scenes/main.tscn", "res://assets/sounds/button-press.wav", "Main scene references press SFX asset")
	_check_contains("scenes/options_modal.tscn", "MusicVolumeSlider", "Options scene has music volume slider")
	_check_contains("scenes/options_modal.tscn", "MusicMutedLabel", "Options scene warns when music is muted")
	_check_contains("scenes/options_modal.tscn", "Music is muted. Raise this slider to hear the background music.", "Muted music warning has visible copy")
	_check_contains("scenes/options_modal.tscn", "SfxVolumeSlider", "Options scene has SFX volume slider")
	_check_contains("scripts/options_modal.gd", "_update_music_muted_warning", "Options updates muted music warning")
	_check_contains("scripts/options_modal.gd", "music_muted_label.visible = value <= 0.001", "Muted music warning follows zero slider value")
	_check_contains("scripts/main.gd", "button.mouse_entered.connect", "Button hover SFX wiring exists")
	_check_contains("scripts/main.gd", "button.pressed.connect", "Button press SFX wiring exists")
	_check_contains("scripts/main.gd", "_pulse_wheel_indicator", "Pointer indicator pulse helper exists")
	_check_contains("scripts/main.gd", "_get_next_wheel_arc_focus", "Indicator effects target the top wheel arc")
	_check_contains("scripts/main.gd", "highest > last_highest_affordable_wheel", "Indicator pulse triggers when a higher wheel becomes affordable")
	_check_contains("scripts/main.gd", "_spawn_indicator_sparkles(focus_point)", "Indicator pulse includes arc sparkles")
	_check_contains("scripts/main.gd", "_spawn_particle_burst(origin, Color(1.0, 0.92, 0.36, 1), 16)", "Indicator sparkle burst is upgraded and gold")
	_check_contains("scripts/wheel.gd", "_draw_segment_labels", "Wheel draws text directly on outcome segments")
	_check_contains("scripts/wheel.gd", "_build_label_sections", "Wheel groups contiguous segment labels")
	_check_contains("scripts/wheel.gd", "_segment_label_value", "Wheel renders outcome values per segment")
	_check_contains("scripts/wheel.gd", "return prefix + UiFormat.compact_number", "Wheel labels use compact symbol-prefixed values")
	_check_not_contains("scripts/wheel.gd", "_segment_label_title", "Wheel no longer draws wordy outcome title labels")
	_check_contains("scripts/wheel.gd", "ThemeDB.fallback_font", "Wheel label rendering uses runtime font access")
	_check_contains("scripts/wheel.gd", "draw_set_transform(center_pos, tangent, Vector2.ONE)", "Wheel labels rotate with segment arc position")
	_check_contains("scripts/wheel.gd", "var spin_locked: bool = false", "Wheel tracks spin lock during coin resolution")
	_check_contains("scripts/wheel.gd", "func can_start_spin() -> bool:", "Wheel exposes spin-availability helper")
	_check_contains("scripts/wheel.gd", "func set_spin_locked(is_locked: bool) -> void:", "Wheel exposes interaction lock setter")
	_check_not_contains("scripts/game.gd", "func get_spin_cost_modifier_lines() -> Array[String]:", "Game no longer exposes the removed spin cost modifier label helper")
	_check_not_contains("scripts/main.gd", "PrevWheelButton", "Indicator polish does not target previous wheel button")
	_check_not_contains("scripts/main.gd", "NextWheelButton", "Indicator polish does not target next wheel button")
	_check_not_contains("scripts/main.gd", "tooltip_text", "Main scene script has no hover tooltips")
	_check_not_contains("scripts/wheel.gd", "tooltip_text", "Wheel script has no hover tooltips")
	_check_not_contains("scripts/shop.gd", "tooltip_text", "Shop script has no hover tooltips")
	_check_not_contains("scripts/end_screen.gd", "tooltip_text", "End screen script has no hover tooltips")
	_check_not_contains("scenes/main.tscn", "tooltip_text", "Main scene has no hover tooltips")
	_check_not_contains("scenes/main.tscn", "CostModifiersLabel", "Main scene no longer has the removed cost modifier label")
	_check_not_contains("scenes/main_menu.tscn", "tooltip_text", "Main menu scene has no hover tooltips")
	_check_not_contains("scenes/tutorial_modal.tscn", "tooltip_text", "Tutorial scene has no hover tooltips")
	_check_not_contains("scenes/options_modal.tscn", "tooltip_text", "Options scene has no hover tooltips")
	_check_not_contains("scenes/shop.tscn", "tooltip_text", "Shop scene has no hover tooltips")
	_check_not_contains("scenes/end_screen.tscn", "tooltip_text", "End screen scene has no hover tooltips")
	_check_contains("scripts/main_menu.gd", "ArrowHead", "Tutorial sign graphic exists")
	_check_contains("scripts/main_menu.gd", "MOUSE_FILTER_IGNORE", "Tutorial sign is click-through")
	_check_contains("scripts/main_menu.gd", "tutorial_button.position = Vector2(viewport_size.x - 62.0, 20.0)", "Tutorial button stays top-right")
	_check_contains("scripts/main_menu.gd", "tutorial_sign.position = Vector2(max(18.0, viewport_size.x - 292.0), tutorial_sign_base_y)", "Tutorial sign points toward tutorial button")
	_check_contains("scripts/main_menu.gd", "tutorial_sign.custom_minimum_size = Vector2(190, 42)", "Tutorial sign has stable graphic size")
	_check_contains("scripts/main_menu.gd", "beam.size = Vector2(108, 10)", "Tutorial sign has graphic beam")
	_check_contains("scripts/main_menu.gd", "head.polygon = PackedVector2Array", "Tutorial sign has arrow head graphic")
	_check_contains("scripts/main_menu.gd", "tutorial_sign_tween.set_loops()", "Tutorial sign bob loops")
	_check_contains("scripts/main_menu.gd", "position:y\", tutorial_sign_base_y - 8.0", "Tutorial sign bobs upward")
	_check_contains("scripts/main_menu.gd", "_set_tutorial_sign_motion_enabled(not bool(settings.get(\"reduced_motion\", false)))", "Tutorial sign respects live reduced motion setting")
	_check_contains("scripts/main_menu.gd", "tutorial_sign_seen", "Tutorial sign uses dedicated seen flag")
	_check_contains("scripts/main_menu.gd", "SaveManager.set_setting(\"tutorial_sign_seen\", true)", "Tutorial sign seen flag is saved")
	_check_contains("scripts/main_menu.gd", "_on_tutorial_pressed", "Tutorial sign dismisses when tutorial opens")
	_check_contains("scripts/main_menu.gd", "tutorial_sign.queue_free()", "Tutorial sign is removed after tutorial opens")
	_check_contains("scripts/main_menu.gd", "history_requested", "Main menu exposes run history signal")
	_check_contains("scripts/main_menu.gd", "credits_requested", "Main menu exposes credits signal")
	_check_contains("scripts/main_menu.gd", "history_button.pressed.connect", "History button emits from main menu")
	_check_contains("scripts/main_menu.gd", "credits_button.pressed.connect", "Credits button emits from main menu")
	_check_contains("scripts/main_menu.gd", "_configure_focus_navigation", "Main menu configures keyboard/controller focus routing")
	_check_contains("scripts/main_menu.gd", "new_game_button.focus_neighbor_right = tutorial_button.get_path()", "Main menu routes focus from New Game to tutorial button")
	_check_contains("scenes/main_menu.tscn", "Run History", "Main menu has Run History button")
	_check_contains("scenes/main_menu.tscn", "Credits", "Main menu has Credits button")
	_check_contains("scripts/main.gd", "main_menu_layer.connect(\"history_requested\", _show_run_history_window)", "Main connects history button to history window")
	_check_contains("scripts/main.gd", "main_menu_layer.connect(\"credits_requested\", _show_credits_window)", "Main connects credits button to credits window")
	_check_contains("scripts/main.gd", "_show_confirmation_window(", "Main exposes reusable confirmation modal helper")
	_check_contains("scripts/main.gd", "_confirm_save_exit_to_main_menu", "Main confirms before Save & Exit")
	_check_contains("scripts/main.gd", "_save_run_and_close_options", "Main supports explicit in-game Save")
	_check_contains("scripts/main.gd", "A saved run exists. Starting a new game will replace it.", "New Game warning copy exists")
	_check_contains("scripts/main.gd", "Save the current run and return to the main menu.", "Save & Exit warning copy exists")
	_check_contains("scripts/main.gd", "func _show_credits_window() -> void:", "Credits modal helper exists")
	_check_contains("scripts/main.gd", "SaveManager.get_run_history()", "Run history window reads saved history")
	_check_contains("scripts/main.gd", "No completed runs yet", "Run history has empty state")
	_check_contains("scripts/main.gd", "_make_history_entry_card", "Run history renders paginated summary cards")
	_check_contains("scripts/main.gd", "Payouts: base", "Run history shows payout breakdown")
	_check_contains("scripts/main.gd", "Spent: spins", "Run history shows spend breakdown")
	_check_contains("scripts/game.gd", "SaveManager.add_run_history(get_run_summary())", "Completed runs are stored in history")
	_check_contains("scripts/game.gd", "\"shop_available\": shop_available", "Save state stores pending shop availability")
	_check_contains("scripts/game.gd", "\"pending_shop_skill_ids\": _pending_shop_skill_ids()", "Save state stores pending shop offer ids")
	_check_contains("scripts/game.gd", "shop_available = bool(state.get(\"shop_available\", false))", "Load state restores pending shop availability")
	_check_contains("scripts/game.gd", "pending_shop_skills = _pending_shop_skills_from_ids", "Load state restores pending shop offers")
	_check_contains("scripts/game.gd", "func set_pending_shop_skill_ids(ids: Array) -> void:", "Game exposes pending shop setter by id")
	_check_contains("scripts/save_manager.gd", "const MAX_RUN_HISTORY := 12", "Run history has bounded size")
	_check_contains("scripts/save_manager.gd", "history.push_front(entry)", "Newest run history appears first")
	_check_contains("scripts/save_manager.gd", "history.pop_back()", "Oldest run history is trimmed")
	_check_contains("scripts/game.gd", "\"final_coins\": coins", "History stores final coins")
	_check_contains("scripts/game.gd", "\"highest_wheel\": max(run_highest_wheel, selected_wheel)", "History stores highest wheel reached")
	_check_contains("scripts/game.gd", "\"skills_bought\": _get_skill_purchase_count()", "History stores skill count")
	_check_contains("scripts/game.gd", "\"base_payout\": run_base_payout", "History stores base payout")
	_check_contains("scripts/game.gd", "\"skill_payout\": run_skill_payout", "History stores skill payout")
	_check_contains("scripts/game.gd", "\"spin_costs\": run_spin_costs", "History stores spin costs")
	_check_contains("scripts/game.gd", "\"shop_spent\": run_shop_spent", "History stores shop spend")
	_check_contains("scripts/game.gd", "run_highest_wheel = max(run_highest_wheel, selected_wheel)", "Highest wheel updates on selection")
	_check_contains("scripts/end_screen.gd", "Coin Breakdown", "End screen displays coin breakdown")
	_check_contains("scripts/end_screen.gd", "CoinBreakdownTitle", "End screen avoids duplicate breakdown insertion")
	_check_contains("scripts/end_screen.gd", "DisplayServer.get_name() != \"headless\"", "End screen skips jackpot audio during headless verification")
	_check_not_contains("scripts/main.gd", "Coin Breakdown", "Coin breakdown is not rendered in main HUD")
	_check_not_contains("scripts/shop.gd", "Coin Breakdown", "Coin breakdown is not rendered in shop")
	_check_not_contains("scripts/wheel.gd", "Coin Breakdown", "Coin breakdown is not rendered on wheel")
	_check_contains("scripts/options_modal.gd", "reduced_motion", "Options emits reduced motion setting")
	_check_contains("scripts/options_modal.gd", "muted_flashes", "Options emits muted flashes setting")
	_check_contains("scripts/options_modal.gd", "large_ui_text", "Options emits larger UI text setting")
	_check_contains("scripts/options_modal.gd", "signal save_requested", "Options exposes explicit save signal")
	_check_contains("scripts/main.gd", "SaveManager.set_setting(key, value)", "Options persist changed settings")
	_check_contains("scripts/main.gd", "_apply_saved_settings()", "Options apply changed settings live")
	_check_contains("scripts/main.gd", "reduced_motion_enabled = bool(settings.get(\"reduced_motion\", false))", "Reduced motion setting updates main state")
	_check_contains("scripts/main.gd", "muted_flashes_enabled = bool(settings.get(\"muted_flashes\", false))", "Muted flashes setting updates main state")
	_check_contains("scripts/main.gd", "large_ui_text_enabled = bool(settings.get(\"large_ui_text\", false))", "Large UI text setting updates main state")
	_check_contains("scripts/main.gd", "get_tree().node_added.connect(_on_node_added)", "Dynamic UI nodes receive polish hooks")
	_check_contains("scripts/main.gd", "_apply_large_ui_text_to_control_deferred", "Dynamic labels and buttons receive large text scaling through safe deferred lookup")
	_check_contains("scripts/main.gd", "node.get_instance_id()", "Dynamic large text deferred hook stores instance id")
	_check_contains("scripts/main.gd", "_apply_large_ui_text(modal_layer)", "Options/tutorial modal receive large text scaling")
	_check_contains("scripts/main.gd", "_apply_large_ui_text(end_screen)", "End screen receives large text scaling")
	_check_contains("scripts/end_screen.gd", "SaveManager.get_setting(\"reduced_motion\")", "End screen intro respects reduced motion")
	_check_contains("scripts/options_modal.gd", "_update_resolution_warning", "Options updates resolution warning")
	_check_contains("scripts/options_modal.gd", "_configure_focus_navigation(in_game)", "Options configure keyboard/controller focus routing")
	_check_contains("scripts/options_modal.gd", "func focus_default_control() -> void:", "Options expose default focus helper for navigation mode")
	_check_contains("scripts/options_modal.gd", "width < 1280 or height < 720", "Resolution warning threshold is cramped below 1280x720")
	_check_contains("scenes/options_modal.tscn", "This resolution may feel cramped", "Resolution warning has visible copy")
	_check_contains("scenes/options_modal.tscn", "ResolutionWarningLabel", "Options scene has resolution warning label")
	_check_contains("project.godot", "window/size/viewport_width=1280", "Project default viewport width is 1280")
	_check_contains("project.godot", "window/size/viewport_height=720", "Project default viewport height is 720")
	_check_contains("project.godot", "window/stretch/mode=\"canvas_items\"", "Project uses canvas_items stretch mode")
	_check_contains("project.godot", "window/stretch/aspect=\"expand\"", "Project uses expand stretch aspect")
	_check_contains("scripts/shop.gd", "_configure_focus_navigation", "Shop configures keyboard/controller focus routing")
	_check_contains("scripts/shop.gd", "button.focus_neighbor_bottom = continue_button.get_path()", "Shop routes skill-card focus down to Continue")
	_check_contains("scripts/end_screen.gd", "_configure_focus_navigation", "End screen configures keyboard/controller focus routing")
	_check_contains("scripts/end_screen.gd", "play_again_button.focus_neighbor_right = main_menu_button.get_path()", "End screen action buttons support left/right controller focus")
	_check_contains("scripts/save_manager.gd", "\"window_mode\": \"windowed\"", "Default window mode is windowed")
	_check_contains("scripts/save_manager.gd", "\"resolution\": \"1280x720\"", "Default saved resolution is 1280x720")
	_check_contains("scripts/save_manager.gd", "\"music_volume\": 0.5", "Default music volume starts at 50 percent")
	_check_contains("scripts/save_manager.gd", "\"sfx_volume\": 0.5", "Default SFX volume starts at 50 percent")
	_check_contains("scenes/options_modal.tscn", "value = 0.5", "Options sliders default to 50 percent")
	for resolution in ["1024x768", "1280x720", "1280x800", "1280x960", "1366x768", "1600x900", "1680x1050", "1920x1080", "1920x1200", "2560x1080", "2560x1440", "2560x1600", "3440x1440", "3840x2160"]:
		_check_contains("scripts/main.gd", "\"" + resolution + "\"", "Resolution option exists: " + resolution)
	_check_contains("scripts/main.gd", "DisplayServer.WINDOW_MODE_FULLSCREEN", "Fullscreen mode is applied through DisplayServer")
	_check_contains("scripts/main.gd", "DisplayServer.WINDOW_MODE_WINDOWED", "Windowed mode is applied through DisplayServer")
	_check_contains("scripts/main.gd", "DisplayServer.window_set_size(Vector2i(width, height))", "Window size applies selected resolution")
	_check_contains("scripts/main.gd", "get_viewport().size_changed.connect(_layout_game_ui)", "Game UI relayouts on viewport resize")
	_check_contains("scripts/main.gd", "func _layout_game_ui(viewport_override: Vector2 = Vector2.ZERO)", "Game layout can be runtime-verified with explicit viewport size")
	_check_contains("scripts/main.gd", "var stats_visible := wheel_node.visible and viewport_size.x >= 980.0", "Game layout uses the widened stats-panel breakpoint")
	_check_contains("scripts/main.gd", "viewport_size.x < 940.0", "Game layout scales wheel for narrow widths")
	_check_contains("scripts/main_menu.gd", "var stacked := viewport_size.x < 980.0", "Main menu uses stacked narrow layout")
	_check_contains("scripts/main_menu.gd", "get_viewport().size_changed.connect(_layout_menu)", "Main menu relayouts on viewport resize")
	_check_contains("scripts/main_menu.gd", "func _layout_menu(viewport_override: Vector2 = Vector2.ZERO)", "Menu layout can be runtime-verified with explicit viewport size")
	_check_contains("scripts/save_manager.gd", "\"tutorial_sign_seen\": false", "Tutorial sign seen flag has default")
	_check_contains("scripts/main.gd", "func _set_navigation_focus_enabled(is_enabled: bool) -> void:", "Main scene tracks keyboard/controller focus mode")
	_check_contains("scripts/main.gd", "release_focus()", "Main scene clears focus borders when mouse input resumes")
	_check_contains("scenes/main_menu.tscn", "res://assets/ui/game-logo.png", "Main menu uses the alpha-safe logo asset")
	_check_file_exists("wheel_balance.md", "Wheel balance snapshot exists")
	_check_contains("wheel_balance.md", "Smoothed cost curve", "Wheel balance snapshot records smoothed balance goal")
	_check_contains("wheel_balance.md", "| W5 | 800 | `+2,006`", "Wheel balance snapshot records smoothed W5 Plus")
	_check_contains("wheel_balance.md", "| W6 | 2,500 | `+6,019`", "Wheel balance snapshot records smoothed W6 Plus")
	_check_contains("wheel_balance.md", "| W7 | 7,500 | `+17,298`", "Wheel balance snapshot records smoothed W7 Plus")
	_check_contains("wheel_balance.md", "| W8 | 22,000 | `+49,016`", "Wheel balance snapshot records smoothed W8 Plus")
	_check_contains("wheel_balance.md", "| W9 | 65,000 | `+140,568`", "Wheel balance snapshot records smoothed W9 Plus")
	_check_contains("scripts/wheel_config.gd", "_mo(\"+2006\", OP_ADD, 2006.0, 53, POSITIVE)", "Wheel config applies smoothed W5 Plus")
	_check_contains("scripts/wheel_config.gd", "_mo(\"+6019\", OP_ADD, 6019.0, 54, POSITIVE)", "Wheel config applies smoothed W6 Plus")
	_check_contains("scripts/wheel_config.gd", "_mo(\"+17298\", OP_ADD, 17298.0, 55, POSITIVE)", "Wheel config applies smoothed W7 Plus")
	_check_contains("scripts/wheel_config.gd", "_mo(\"+49016\", OP_ADD, 49016.0, 56, POSITIVE)", "Wheel config applies smoothed W8 Plus")
	_check_contains("scripts/wheel_config.gd", "_mo(\"+140568\", OP_ADD, 140568.0, 58, POSITIVE)", "Wheel config applies smoothed W9 Plus")
	_check_contains("release-plan.md", "## Active Polish Task List", "Release plan has active polish task list")
	_check_contains("release-plan.md", "Fix sequential skill coin modifiers", "Release plan tracks sequential skill fix")
	_check_contains("release-plan.md", "Replace the first-run tutorial text callout with a graphic treatment.", "Release plan tracks tutorial graphic treatment")
	_check_contains("release-plan.md", "Redesign Run History", "Release plan tracks run history redesign")
	_check_contains("release-plan.md", "Rework the higher-wheel indicator sparkle/pulse", "Release plan tracks indicator visibility work")
	_check_contains("release-plan.md", "Default BGM and SFX volumes to 50%", "Release plan tracks lower default volumes")
	_check_contains("release-plan.md", "Replace the separate probability table with text displayed directly on the wheel segments", "Release plan tracks wheel-embedded labels")
	_check_scene_has("scenes/main.tscn", [
		"Wheel/PointerArrow/PointerIndicator",
		"StatsPanel/StatsVBox/UpgradesScroll/UpgradesVBox",
		"InGameOptionsButton",
		"InGameHelpButton",
	], "Main scene required polish nodes")
	_check_scene_has("scenes/main_menu.tscn", [
		"MenuPanel/MenuVBox/HistoryButton",
		"TutorialButton",
	], "Main menu required polish nodes")
	_check_scene_has("scenes/options_modal.tscn", [
		"CenterContainer/Panel/VBox/ResolutionWarningLabel",
		"CenterContainer/Panel/VBox/MusicMutedLabel",
		"CenterContainer/Panel/VBox/ReducedMotionCheck",
		"CenterContainer/Panel/VBox/MutedFlashesCheck",
		"CenterContainer/Panel/VBox/LargeUiTextCheck",
	], "Options scene accessibility nodes")
	_check_scene_has("scenes/end_screen.tscn", [
		"EndLayout/Panel/Content/BodyRow/OutcomePanel/VBox/OutcomeRows",
		"EndLayout/Panel/Content/BodyRow/BuildPanel/VBox/BuildScroll/SkillGrid",
	], "End screen required breakdown/history nodes")
	_check_positive_outcomes_can_cover_spin_costs()

	if failures.is_empty():
		print("Polish smoke verification passed.")
		quit(0)
	else:
		for failure in failures:
			push_error(failure)
		quit(1)

func _read(path: String) -> String:
	var file := FileAccess.open("res://" + path, FileAccess.READ)
	if file == null:
		failures.append("Cannot open " + path)
		return ""
	return file.get_as_text()

func _check_contains(path: String, needle: String, label: String) -> void:
	var text := _read(path)
	if text.find(needle) == -1:
		failures.append(label + " missing in " + path + ": " + needle)

func _check_not_contains(path: String, needle: String, label: String) -> void:
	var text := _read(path)
	if text.find(needle) != -1:
		failures.append(label + " still present in " + path + ": " + needle)

func _check_file_exists(path: String, label: String) -> void:
	if not FileAccess.file_exists("res://" + path):
		failures.append(label + " missing: " + path)

func _check_positive_outcomes_can_cover_spin_costs() -> void:
	for wheel_num in range(2, 10):
		var cost := WheelConfig.get_cost(wheel_num)
		var has_covering_positive := false
		for outcome in WheelConfig.get_outcomes(wheel_num):
			var op := int(outcome[WheelConfig.IDX_OP])
			var value := int(round(float(outcome[WheelConfig.IDX_VALUE])))
			if op == WheelConfig.OP_ADD and value > cost:
				has_covering_positive = true
			elif op == WheelConfig.OP_MULTIPLY and cost * value > cost:
				has_covering_positive = true
		if not has_covering_positive:
			failures.append("No positive outcome can cover spin cost on W%d: cost %d" % [wheel_num, cost])

func _check_scene_has(path: String, node_paths: Array[String], label: String) -> void:
	var text := _read(path)
	if text.is_empty():
		return
	for node_path in node_paths:
		var parts := node_path.split("/")
		var node_name := parts[parts.size() - 1]
		var parent_parts: Array[String] = []
		for index in range(parts.size() - 1):
			parent_parts.append(parts[index])
		var parent_path := "/".join(parent_parts)
		var node_marker := "[node name=\"" + node_name + "\""
		if text.find(node_marker) == -1:
			failures.append(label + " missing node " + node_name + " in " + path)
			continue
		if not parent_path.is_empty() and text.find("parent=\"" + parent_path + "\"") == -1:
			failures.append(label + " missing parent " + parent_path + " for " + node_name + " in " + path)
